apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-deploy-autoscale
  labels:
    app: kekw
spec:
  selector:
    matchLabels:
      app: awooga
  template:
    metadata:
      labels:
        app: awooga
    spec:
      containers:
      - name: awooga-app
        image: iamadite/k8sphptest:latest
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: k8s-app-deploy-autoscale
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
        