apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deploy-autoscale
  labels:
    app: my-k8s-deploy
spec:
  selector:
    matchLabels:
      project: pog
  template:
    metadata:
      labels:
        project: pog # Service will look for this label
    spec:
      containers:
        - name : pog-web
          image: iamadite/k8sphptest:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: my-web-deploy-autoscale
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscale-pod-service
  labels:
    env  : prod
    owner: Pavel
spec:
  type: LoadBalancer
  selector:
    project: pog # SELECT PODS WITH LABELS
  ports:
    - name      : my-pog-app-listener
      protocol  : TCP
      port      : 80 # LOADBALANCER PORT
      targetPort: 80 # POD's PORT