apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-deploy
spec:
  selector:
    matchLabels:
      project: kekW
  template:
    metadata:
      labels:
        project: kekW # Service will look for this label
    spec:
      containers:
        - name : my-web
          image: iamadite/k8sphptest:latest
          ports:
            - containerPort: 80

        - name : other-web
          image: tomcat:8.5.38
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-multi-pod-service
  labels:
    env  : prod
    owner: Pavel
spec:
  type: LoadBalancer
  selector:
    project: kekW # SELECT PODS WITH LABELS
  ports:
    - name      : my-web-app-listener
      protocol  : TCP
      port      : 80 # LOADBALANCER PORT
      targetPort: 80 # POD's PORT

    - name      : other-web-app-listener
      protocol  : TCP
      port      : 8888 # LOADBALANCER PORT
      targetPort: 8080 # POD's PORT
