apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-deploy
spec:
  selector:
    matchLabels:
      project: kek
  template:
    metadata:
      labels:
        project: kek # Service will look for this label
    spec:
      containers:
        - name : kek-web
          image: iamadite/k8sphptest:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env  : prod
    owner: Pavel
spec:
  selector:
    project: kek # SELECT PODS WITH LABELS
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80 # LOADBALANCER PORT
      targetPort: 80 # POD's PORT
  type: LoadBalancer