apiVersion: v1  
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env  : prod
    owner: pavel
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: {{ .Release.Name }}-listener-main
    
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: {{ .Release.Name }}-listener-cat
  selector:
    project: {{ .Release.Name }}
